/**
 * Verified accommodation names from the official LES Borovoe accommodation page.
 * Room numbers and counts below are demo inventory labels only; real unit numbers
 * were not published. Forest House rooms are separate sellable units, as on the
 * official page (two double rooms and one six-person room).
 */
export const lesBorovoeUnitTypes = [
  { name: "A-Frame", prefix: "A-", firstNumber: 101, count: 5, capacity: 4, rateCode: "acc_a_frame", demoNightlyRate: 130000,
    agentKnowledge: { shortDescription: "Треугольный домик внутри леса, до 4 гостей.", occupancyDescription: "2 взрослых и 2 подростка или взрослых гостя.", recommendedFor: ["гостей, которым важен формат внутри леса", "подростков и взрослых"], notRecommendedFor: ["маленьких детей или пожилых гостей на втором ярусе"], bedLayout: "Первый уровень: раскладной двухместный диван; второй ярус: двуспальное место.", locationDescription: "Расположен внутри леса.", features: ["подвесная качеля", "печь-камин", "санузел с душем", "терраса", "тёплый пол", "телевизор", "Wi-Fi", "кондиционер", "чайная зона", "мини-бар"], sellingPoints: ["печь-камин", "расположение внутри леса"], warnings: ["На втором ярусе низкий потолок, крутая лестница и нет ограждения.", "Тёплый чан доступен по сезону за дополнительную плату; нагрев занимает около 5 часов.", "Ванна на террасе доступна по сезону."], source: "https://leshotelborovoe.kz/prozhivanie/" } },
  { name: "Nest House", prefix: "N-", firstNumber: 201, count: 5, capacity: 4, rateCode: "acc_nest_house", demoNightlyRate: 210000,
    agentKnowledge: { shortDescription: "Домик напротив леса для 2 взрослых и 2 детей или подростков.", occupancyDescription: "До 4 гостей: 2 взрослых и 2 ребёнка или подростка.", recommendedFor: ["семей с детьми или подростками"], notRecommendedFor: [], bedLayout: "Первый уровень: двуспальная кровать; второй ярус: двуспальное место.", locationDescription: "Расположен напротив леса.", features: ["панорамное окно на потолке", "санузел с душем", "терраса", "тёплый пол", "телевизор", "Wi-Fi", "кондиционер", "чайная зона", "мини-бар"], sellingPoints: ["дизайн в форме гнезда", "панорамное окно на потолке"], warnings: ["На втором ярусе низкий потолок и крутая лестница; место оборудовано ограждёнными перилами и лучше подходит для детей и подростков."], source: "https://leshotelborovoe.kz/prozhivanie/" } },
  { name: "Glass House", prefix: "G-", firstNumber: 301, count: 5, capacity: 4, rateCode: "acc_glass_house", demoNightlyRate: 135000,
    agentKnowledge: { shortDescription: "Домик напротив леса для 2 взрослых и 2 детей.", occupancyDescription: "До 4 гостей: 2 взрослых и 2 ребёнка.", recommendedFor: ["семей с детьми", "гостей, которым важна ванная с видом на лес"], notRecommendedFor: ["взрослых или пожилых гостей на втором ярусе"], bedLayout: "Первый уровень: двуспальная кровать; второй ярус: двуспальное место.", locationDescription: "Расположен напротив леса.", features: ["ванная комната с панорамным видом на лес", "терраса", "тёплый пол", "телевизор", "Wi-Fi", "кондиционер", "чайная зона", "мини-бар"], sellingPoints: ["ванная комната с панорамным видом на лес", "необычный стеклянный дизайн"], warnings: ["На втором ярусе низкий потолок и крутая лестница; он рассчитан для маленьких детей и не подходит взрослым или пожилым гостям."], source: "https://leshotelborovoe.kz/prozhivanie/" } },
  { name: "Forest House · 2-местный номер", prefix: "F-", firstNumber: 401, count: 2, capacity: 2, rateCode: "acc_forest_double", demoNightlyRate: 135000,
    agentKnowledge: { shortDescription: "Отдельный двухместный номер в Forest House.", occupancyDescription: "До 2 гостей.", recommendedFor: ["одного или двух гостей"], notRecommendedFor: [], bedLayout: "Отдельная спальня с двуспальной кроватью.", locationDescription: "Напротив леса; номера находятся в общем доме с отдельными входами в каждый номер.", features: ["отдельный санузел с душем", "терраса", "тёплый пол", "телевизор", "Wi-Fi", "кондиционер", "чайная зона", "мини-бар"], sellingPoints: ["отдельный номер в Forest House"], warnings: [], source: "https://leshotelborovoe.kz/prozhivanie/" } },
  { name: "Forest House · 6-местный номер", prefix: "F-", firstNumber: 403, count: 1, capacity: 6, rateCode: "acc_forest_six", demoNightlyRate: 245000,
    agentKnowledge: { shortDescription: "Отдельный шестиместный номер в Forest House.", occupancyDescription: "До 6 гостей; весь дом можно арендовать компанией до 10 человек, размещаясь в отдельных номерах.", recommendedFor: ["семей или компаний до 6 гостей"], notRecommendedFor: [], bedLayout: "Две отдельные спальни с двуспальными кроватями и гостиная с раскладным диваном.", locationDescription: "Напротив леса; номера находятся в общем доме с отдельными входами в каждый номер.", features: ["отдельный санузел с душем", "терраса", "тёплый пол", "телевизор", "Wi-Fi", "кондиционер", "чайная зона", "мини-бар"], sellingPoints: ["две отдельные спальни", "гостиная с раскладным диваном"], warnings: [], source: "https://leshotelborovoe.kz/prozhivanie/" } },
] as const;

export const lesBorovoeLegacyCategoryNames = ["Премиум-домик", "Стандартный домик", "Семейный коттедж", "Люкс-шале"] as const;
